[package]
name = "testcrate"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
path = "lib.rs"

[dependencies]
futures-await = { path = ".." }

[dev-dependencies]
compiletest_rs = "0.3"

[[test]]
name = "ui"
harness = false
