[package]
name = "futures-channel"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://github.com/rust-lang-nursery/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
Channels for asynchronous communication using futures-rs.
"""

[features]
std = ["futures-core/std"]
default = ["std"]

[dependencies]
futures-core = { path = "../futures-core", version = "0.2.0", default-features = false }

[dev-dependencies]
futures = { path = "../futures", version = "0.2.0", default-features = true }
futures-executor = { path = "../futures-executor", version = "0.2.0", default-features = true }
