cargo-features = ["edition"]

[package]
name = "futures-channel-preview"
edition = "2018"
version = "0.3.0-alpha.2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-doc/0.3.0-alpha.2/futures_channel"
description = """
Channels for asynchronous communication using futures-rs.
"""

[lib]
name = "futures_channel"

[features]
std = ["futures-core-preview/std"]
default = ["std"]

[dependencies]
futures-core-preview = { path = "../futures-core", version = "0.3.0-alpha.2", default-features = false }

[dev-dependencies]
futures-preview = { path = "../futures", version = "0.3.0-alpha.2", default-features = true }
