[package]
name = "futures-channel-preview"
edition = "2018"
version = "0.3.0-alpha.18"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures_channel"
description = """
Channels for asynchronous communication using futures-rs.
"""

[lib]
name = "futures_channel"

[features]
default = ["std"]
std = ["alloc", "futures-core-preview/std"]
alloc = ["futures-core-preview/alloc"]
sink = ["futures-sink-preview"]

# Unstable features
# These features are outside of the normal semver guarantees and require the
# `unstable` feature as an explicit opt-in to unstable API.
unstable = ["futures-core-preview/unstable"]
cfg-target-has-atomic = ["futures-core-preview/cfg-target-has-atomic"]

[dependencies]
futures-core-preview = { path = "../futures-core", version = "=0.3.0-alpha.18", default-features = false }
futures-sink-preview = { path = "../futures-sink", version = "=0.3.0-alpha.18", default-features = false, optional = true }

[dev-dependencies]
futures-preview = { path = "../futures", version = "=0.3.0-alpha.18", default-features = true }
futures-test-preview = { path = "../futures-test", version = "=0.3.0-alpha.18", default-features = true }
