[package]
name = "futures-example-imperative"
edition = "2018"
version = "0.3.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
keywords = ["futures", "async", "future"]
repository = "https://github.com/rust-lang/futures-rs"
homepage = "https://rust-lang.github.io/futures-rs"
documentation = "https://docs.rs/futures/0.3.0"
description = """
An implementation of futures and streams featuring zero allocations,
composability, and iterator-like interfaces.
"""
categories = ["asynchronous"]
publish = false

[dependencies]
futures = { path = "../../futures", version = "0.3.0", features = ["thread-pool"] }
