[package]
name = "futures-async-macro"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
proc-macro = true

[dependencies]
quote = { git = 'https://github.com/dtolnay/quote' }
proc-macro2 = { git = 'https://github.com/alexcrichton/proc-macro2' }


[dependencies.syn]
git = 'https://github.com/alexcrichton/syn'
branch = 'yield'
features = ["full", "fold"]
