[package]
name = "futures"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["futures", "async", "future"]
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://github.com/rust-lang-nursery/futures-rs"
documentation = "https://docs.rs/futures"
description = """
An implementation of futures and streams featuring zero allocations,
composability, and iterator-like interfaces.
"""
categories = ["asynchronous"]

[badges]
travis-ci = { repository = "rust-lang-nursery/futures-rs" }
appveyor = { repository = "rust-lang-nursery/futures-rs" }

[dependencies]
# futures-async-runtime = { path = "../futures-async-runtime", version = "0.2.0", default-features = false }
futures-core = { path = "../futures-core", version = "0.2.0", default-features = false }
futures-channel = { path = "../futures-channel", version = "0.2.0", default-features = false }
futures-executor = { path = "../futures-executor", version = "0.2.0", default-features = false }
futures-io = { path = "../futures-io", version = "0.2.0", default-features = false }
futures-sink = { path = "../futures-sink", version = "0.2.0", default-features = false }
futures-stable = { path = "../futures-stable", version = "0.2.0", default-features = false }
futures-util = { path = "../futures-util", version = "0.2.0", default-features = false }
# futures-macro-async = { path = "../futures-macro-async", version = "0.2.0", optional = true }
# futures-macro-await = { path = "../futures-macro-await", version = "0.2.0", optional = true }

[features]
nightly = ["futures-core/nightly", "futures-stable/nightly"]
std = ["futures-core/std", "futures-executor/std", "futures-io/std", "futures-sink/std", "futures-stable/std", "futures-util/std"]
default = ["std"]

# TODO(cramertj) reenable on nightly
# , "futures-async-runtime/nightly", "futures-macro-async", "futures-macro-await", "futures-macro-async/nightly"

# TODO(cramertj) reenable on std
# "futures-async-runtime/std"
