[package]
name = "futures-await-await-macro"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/futures-await"
description = """
Definition of the `await!` macro for the `futures-await` crate.
"""
