[package]
name = "futures-macro"
edition = "2018"
version = "0.3.1"
authors = ["Taylor Cramer <cramertj@google.com>", "Taiki Endo <te316e89@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://docs.rs/futures-macro/0.3.0"
description = """
The futures-rs procedural macro implementations.
"""

[lib]
name = "futures_macro"
proc-macro = true

[features]

[dependencies]
proc-macro2 = "1.0"
proc-macro-hack = "0.5.9"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
