cargo-features = ["edition"]

[package]
name = "futures-sink-preview"
edition = "2018"
version = "0.3.0-alpha.2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-doc/0.3.0-alpha.2/futures_sink"
description = """
The asynchronous `Sink` trait for the futures-rs library.
"""

[lib]
name = "futures_sink"

[features]
std = ["either/use_std", "futures-core-preview/std", "futures-channel-preview/std"]
default = ["std"]

[dependencies]
either = { version = "1.4", default-features = false, optional = true }
futures-core-preview = { path = "../futures-core", version = "0.3.0-alpha.2", default-features = false }
futures-channel-preview = { path = "../futures-channel", version = "0.3.0-alpha.2", default-features = false }
